name: Metrics
on:
  # Schedule daily updates at midnight
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual runs
  workflow_dispatch:
  # Run when you push to the main branch
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # STAT 1: The 3D Isometric Calendar
      - name: 3D Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: Asia/Kolkata

      # STAT 2: Detailed Languages & Habits
      - name: Languages and Habits
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_details: percentage
          config_timezone: Asia/Kolkata
